CC = gcc
CFLAGS = -Wall -Werror -std=c99

all: 4-pfister-a2 4-pfister-a3 4-pfister-a4 4-pfister-a5

# $(RM) is predifined on most systems
clean:
	$(RM) 4-pfister-a2 4-pfister-a3 4-pfister-a4 4-pfister-a5

# make knows all of this (so basically nothing but CFLAGS and CC needed)
# Look at the GIT repo

# % is used for placeholder of anything.c in this case
# %: %.c
#	$(CC) $(CFLAGS) -o $@ $^

# main: main.c
#	$(CC) $(CFLAGS) -o $@ $^

# this is a comment
# main2: main2.c
#	$(CC) $(CFLAGS) -o $@ $^