CC = gcc
CFLAGS = -Wall -Werror -std=c99

all: 4-pfister-a2 4-pfister-a3 4-pfister-a4 4-pfister-a5 4-pfister-a6

# $(RM) is predifined on most systems
clean:
	$(RM) 4-pfister-a2 4-pfister-a3 4-pfister-a4 4-pfister-a5 4-pfister-a6

